### PR TITLE
Update wrap-tool.Rmd

### PR DESCRIPTION
**Pull request by javibio-git**
Added lead and AnVIL coordinator names

### CODE REVIEW

**Comment by javibio-git** [comment]
@avahoffman @cutsort The branch for this PR, is now some changes behind. Would you recommend create a new one? or is it possible to merge this PR without any issues? or maybe there are more options I am not seeing. 

Maybe create a new one including now Allie's blurb?

**Comment by avahoffman** [comment]
> @avahoffman @cutsort The branch for this PR, is now some changes behind. Would you recommend create a new one? or is it possible to merge this PR without any issues? or maybe there are more options I am not seeing.
> 
> Maybe create a new one including now Allie's blurb?

You should merge main into this branch to catch it up. We can show you how to do this if you aren't sure!

**Comment by javibio-git** [comment]
> > @avahoffman @cutsort The branch for this PR, is now some changes behind. Would you recommend create a new one? or is it possible to merge this PR without any issues? or maybe there are more options I am not seeing.
> > Maybe create a new one including now Allie's blurb?
> 
> You should merge main into this branch to catch it up. We can show you how to do this if you aren't sure!

I see! so it is possible to update this branch. I'd prefer you show me how to do it, I don't want to mess up things :). Thank you!

**Comment by avahoffman** [comment]
I will message you!

**Comment by javibio-git** [comment]
@avahoffman merge successful 🎊. Let me know whenever this PR is ready to be merged to main 🙂

**Comment by avahoffman** [comment]
Let's do it!

**Pull request merged**
