### PR TITLE
add blurb to wrap-tool.Rmd

### PR DESCRIPTION
**Pull request by javibio-git**
Added Allie's blurb for the wrap-a-tool cofest

### CODE REVIEW

**Comment by avahoffman** [comment]
@javibio-git do you know how to resolve the spelling errors? If not, let me know!

**Comment by javibio-git** [comment]
> @javibio-git do you know how to resolve the spelling errors? If not, let me know!

@avahoffman I think I just need to add the unknown words to `resources/dictionary.txt`, right? But not sure if I should do it in my branch or in `main` directly.

**Comment by avahoffman** [comment]
> > @javibio-git do you know how to resolve the spelling errors? If not, let me know!
> 
> @avahoffman I think I just need to add the unknown words to `resources/dictionary.txt`, right? But not sure if I should do it in my branch or in `main` directly.

Yes exactly! You should do this on your branch.

**Comment by javibio-git** [comment]
> > > @javibio-git do you know how to resolve the spelling errors? If not, let me know!
> > 
> > 
> > @avahoffman I think I just need to add the unknown words to `resources/dictionary.txt`, right? But not sure if I should do it in my branch or in `main` directly.
> 
> Yes exactly! You should do this on your branch.

Thank you for the clarification! @avahoffman

**Review by avahoffman — APPROVED** [review]
LGTM! Although not sure why the new stuff isn't showing up in the preview.

**Pull request merged**
